### ISSUE TITLE
integrating React-query for api calls

### ISSUE THREAD

**Issue by rahulxdemon** [HamzaMasood7/Space-Chronicles#13]
want to add react-query integration to the api calls 🚀

**Comment by HamzaMasood7** [comment]
yes, you can add. can you brief on which API you will be adding?

**Comment by rahulxdemon** [comment]
```typescript
  const [data, setData] = useState<PicDay | null>(null); 
   useEffect(() => { 
     const apiUrl = 'http://localhost:5000/earth/today'; 
  
  
  
     axios 
       .get(apiUrl) 
       .then((response) => { 
         const responseData: PicDay = response.data; 
         setData(responseData); 
       }) 
       .catch((error) => { 
         console.error('Error fetching data:', error); 
         setData(null); 
       }); 
   }, []);
```

I would like to use react-query for this fetch call

**Comment by HamzaMasood7** [comment]
ok. you can create it.

**Comment by rahulxdemon** [comment]
yes 🍁

**Comment by rahulxdemon** [comment]
I am new to nest.js and prisma but I am getting this error, can you tell me how to resolve
I am getting the error when I start the server using the command
```bash
pnpm run start
```
![image](https://github.com/HamzaMasood7/Space-Chronicles/assets/87606332/17da374b-66f1-45ef-b191-d05c826a192a)

**Comment by HamzaMasood7** [comment]
install prisma,
apply prisma migrations
`npx prisma migrate status`
check if prisma is working and migrations status.
it will create the table in database.

**Comment by rahulxdemon** [comment]
@HamzaMasood7 I am getting this
still getting the error
![image](https://github.com/HamzaMasood7/Space-Chronicles/assets/87606332/7307c4c2-0513-4207-b10e-572600b65747)

**Comment by HamzaMasood7** [comment]
prisma is not installed.
its giving error prisma command not found.

see this link.
https://www.prisma.io/docs/guides/migrate/developing-with-prisma-migrate

**Comment by rahulxdemon** [comment]
> prisma is not installed. its giving error prisma command not found.
> 
> see this link. https://www.prisma.io/docs/guides/migrate/developing-with-prisma-migrate

thanks for the support, it worked
![image](https://github.com/HamzaMasood7/Space-Chronicles/assets/87606332/dda3839a-bf5c-4bf8-b862-ec375911cb4d)

**Comment by rahulxdemon** [comment]
@HamzaMasood7 I have completed the react-query integration and made a PR #17 

here is the video after integrating react-query

https://github.com/HamzaMasood7/Space-Chronicles/assets/87606332/5d619010-2371-44c3-af11-a11df80faa2f
